'use client';

import { useState } from 'react';
import { FileText, CheckCircle, Clock, AlertTriangle, XCircle, ChevronRight, MapPin, RefreshCw } from 'lucide-react';
import { StatusBadge, SeverityBadge } from '@/components/ui/SeverityBadge';
import { toast } from 'sonner';

interface ComplaintActivity {
  id: string;
  potholeId: string;
  severity: 'Dangerous' | 'Moderate' | 'Minor';
  location: string;
  coordinates: string;
  status: 'Detected' | 'Reported' | 'Under Review' | 'Repair Scheduled' | 'Repaired' | 'Closed' | 'Rejected';
  department: string;
  filedAt: string;
  lastUpdated: string;
  autoGenerated: boolean;
}

// Backend integration: GET /api/complaints?user_id=current
const MOCK_COMPLAINTS: ComplaintActivity[] = [
  {
    id: 'CMP-0047',
    potholeId: 'PTH-011',
    severity: 'Dangerous',
    location: 'NH-30, Sector 4 Bypass, Raipur',
    coordinates: '21.2581, 81.6362',
    status: 'Reported',
    department: 'PWD Raipur Division',
    filedAt: '2026-03-13T10:24:00',
    lastUpdated: '2026-03-13T10:24:00',
    autoGenerated: true,
  },
  {
    id: 'CMP-0046',
    potholeId: 'PTH-010',
    severity: 'Moderate',
    location: 'Main Road, Telibandha, Raipur',
    coordinates: '21.2574, 81.6355',
    status: 'Under Review',
    department: 'Municipal Corp. Raipur',
    filedAt: '2026-03-12T16:47:00',
    lastUpdated: '2026-03-13T08:15:00',
    autoGenerated: true,
  },
  {
    id: 'CMP-0045',
    potholeId: 'PTH-007',
    severity: 'Dangerous',
    location: 'Main Road, Pandri, Raipur',
    coordinates: '21.2553, 81.6332',
    status: 'Repair Scheduled',
    department: 'PWD Raipur Division',
    filedAt: '2026-03-11T09:30:00',
    lastUpdated: '2026-03-12T14:22:00',
    autoGenerated: true,
  },
  {
    id: 'CMP-0044',
    potholeId: 'PTH-005',
    severity: 'Moderate',
    location: 'Ring Road, Shankar Nagar, Raipur',
    coordinates: '21.2539, 81.6319',
    status: 'Repair Scheduled',
    department: 'NHAI Regional Office',
    filedAt: '2026-03-10T14:15:00',
    lastUpdated: '2026-03-12T09:45:00',
    autoGenerated: false,
  },
  {
    id: 'CMP-0043',
    potholeId: 'PTH-004',
    severity: 'Dangerous',
    location: 'NH-30, Km 14, Raipur',
    coordinates: '21.2531, 81.6311',
    status: 'Under Review',
    department: 'PWD Raipur Division',
    filedAt: '2026-03-09T11:20:00',
    lastUpdated: '2026-03-11T16:30:00',
    autoGenerated: true,
  },
  {
    id: 'CMP-0041',
    potholeId: 'PTH-001',
    severity: 'Dangerous',
    location: 'NH-30, Km 12, Raipur',
    coordinates: '21.2513, 81.6293',
    status: 'Reported',
    department: 'PWD Raipur Division',
    filedAt: '2026-03-08T08:45:00',
    lastUpdated: '2026-03-08T08:45:00',
    autoGenerated: true,
  },
  {
    id: 'CMP-0039',
    potholeId: 'PTH-009',
    severity: 'Minor',
    location: 'Shankar Nagar Rd, Raipur',
    coordinates: '21.2568, 81.6348',
    status: 'Closed',
    department: 'Municipal Corp. Raipur',
    filedAt: '2026-03-05T13:10:00',
    lastUpdated: '2026-03-10T10:00:00',
    autoGenerated: false,
  },
  {
    id: 'CMP-0038',
    potholeId: 'PTH-008',
    severity: 'Moderate',
    location: 'Airport Rd, Raipur',
    coordinates: '21.2561, 81.6341',
    status: 'Repaired',
    department: 'NHAI Regional Office',
    filedAt: '2026-03-04T10:00:00',
    lastUpdated: '2026-03-12T15:30:00',
    autoGenerated: true,
  },
];

function formatRelativeTime(dateStr: string): string {
  const now = new Date('2026-03-13T14:51:02');
  const date = new Date(dateStr);
  const diffMs = now.getTime() - date.getTime();
  const diffHrs = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffHrs / 24);
  if (diffHrs < 1) return 'Just now';
  if (diffHrs < 24) return `${diffHrs}h ago`;
  if (diffDays === 1) return 'Yesterday';
  return `${diffDays} days ago`;
}

const STATUS_ICONS = {
  Detected: Clock,
  Reported: FileText,
  'Under Review': Clock,
  'Repair Scheduled': AlertTriangle,
  Repaired: CheckCircle,
  Closed: CheckCircle,
  Rejected: XCircle,
};

export default function ComplaintsActivityFeed() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);

  const handleRefresh = async () => {
    setRefreshing(true);
    // Backend integration: re-fetch GET /api/complaints
    await new Promise((r) => setTimeout(r, 1200));
    setRefreshing(false);
    toast.success('Complaints refreshed');
  };

  const handleViewComplaint = (id: string) => {
    toast.info(`Opening complaint ${id}…`);
  };

  return (
    <div className="card">
      <div className="flex items-center justify-between px-5 py-4 border-b border-border/60">
        <div>
          <h2 className="text-base font-600 text-text">Complaints Activity</h2>
          <p className="text-xs text-muted-foreground">{MOCK_COMPLAINTS.length} complaints · auto-generated by AI</p>
        </div>
        <button
          onClick={handleRefresh}
          disabled={refreshing}
          className="p-2 rounded-lg hover:bg-surface-elevated text-muted-foreground hover:text-text transition-colors disabled:opacity-50"
          title="Refresh complaints"
        >
          <RefreshCw size={15} className={refreshing ? 'animate-spin' : ''} />
        </button>
      </div>

      <div className="divide-y divide-border/30 max-h-[480px] overflow-y-auto">
        {MOCK_COMPLAINTS.map((complaint) => {
          const StatusIcon = STATUS_ICONS[complaint.status];
          const isExpanded = expanded === complaint.id;

          return (
            <div key={complaint.id} className="hover:bg-surface-elevated/40 transition-colors">
              <button
                className="w-full text-left px-5 py-4"
                onClick={() => setExpanded(isExpanded ? null : complaint.id)}
              >
                <div className="flex items-start gap-3">
                  {/* Status icon */}
                  <div className={`mt-0.5 flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center ${
                    complaint.status === 'Repaired' || complaint.status === 'Closed' ? 'bg-success/15' :
                    complaint.status === 'Rejected' ? 'bg-destructive/15' :
                    complaint.status === 'Repair Scheduled' ? 'bg-warning/15' :
                    complaint.status === 'Under Review'? 'bg-info/15' : 'bg-surface-elevated'
                  }`}>
                    <StatusIcon size={15} className={
                      complaint.status === 'Repaired' || complaint.status === 'Closed' ? 'text-success' :
                      complaint.status === 'Rejected' ? 'text-destructive' :
                      complaint.status === 'Repair Scheduled' ? 'text-warning' :
                      complaint.status === 'Under Review'? 'text-info' : 'text-muted-foreground'
                    } />
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-2 mb-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-mono text-xs font-600 text-primary">{complaint.id}</span>
                        <SeverityBadge severity={complaint.severity} size="sm" />
                        {complaint.autoGenerated && (
                          <span className="text-[10px] px-1.5 py-0.5 rounded bg-surface-elevated text-muted-foreground border border-border/60">
                            AI auto-filed
                          </span>
                        )}
                      </div>
                      <span className="text-[11px] text-muted-foreground flex-shrink-0">
                        {formatRelativeTime(complaint.lastUpdated)}
                      </span>
                    </div>
                    <p className="text-xs font-500 text-text/80 truncate flex items-center gap-1 mb-1">
                      <MapPin size={10} className="text-muted-foreground flex-shrink-0" />
                      {complaint.location}
                    </p>
                    <div className="flex items-center justify-between">
                      <StatusBadge status={complaint.status} size="sm" />
                      <ChevronRight
                        size={14}
                        className={`text-muted-foreground transition-transform duration-200 ${isExpanded ? 'rotate-90' : ''}`}
                      />
                    </div>
                  </div>
                </div>
              </button>

              {/* Expanded detail */}
              {isExpanded && (
                <div className="px-5 pb-4 fade-in">
                  <div className="ml-11 card-elevated p-4 space-y-3">
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <p className="stat-label mb-1">Pothole ID</p>
                        <p className="font-mono text-xs text-primary">{complaint.potholeId}</p>
                      </div>
                      <div>
                        <p className="stat-label mb-1">Department</p>
                        <p className="text-xs text-text">{complaint.department}</p>
                      </div>
                      <div>
                        <p className="stat-label mb-1">Coordinates</p>
                        <p className="font-mono text-xs text-info">{complaint.coordinates}</p>
                      </div>
                      <div>
                        <p className="stat-label mb-1">Filed</p>
                        <p className="text-xs text-text-secondary">{new Date(complaint.filedAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
                      </div>
                    </div>

                    {/* Auto-generated complaint text */}
                    <div className="p-3 rounded-xl bg-background border border-border/40">
                      <p className="stat-label mb-2">Auto-generated complaint text</p>
                      <p className="text-xs text-text-secondary leading-relaxed font-mono">
                        {complaint.severity} pothole detected at coordinates {complaint.coordinates}.
                        {'\n'}Location: {complaint.location}.
                        {'\n'}Severity: {complaint.severity}. Confidence: {complaint.severity === 'Dangerous' ? '94%' : complaint.severity === 'Moderate' ? '85%' : '74%'}.
                        {'\n'}Evidence images attached. Immediate attention required.
                      </p>
                    </div>

                    <button
                      onClick={() => handleViewComplaint(complaint.id)}
                      className="btn-ghost text-xs py-1.5 px-3 w-full justify-center"
                    >
                      <FileText size={12} />
                      View Full Complaint
                    </button>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}