'use client';

import { Upload, MapPin, FileText, AlertTriangle, TrendingUp, TrendingDown } from 'lucide-react';
import Icon from '@/components/ui/AppIcon';


interface KPICardProps {
  label: string;
  value: string | number;
  subtext: string;
  icon: React.ComponentType<{ size?: number; className?: string }>;
  trend?: { value: number; direction: 'up' | 'down'; good?: boolean };
  variant?: 'default' | 'alert' | 'success' | 'info';
  className?: string;
}

function KPICard({ label, value, subtext, icon: Icon, trend, variant = 'default', className = '' }: KPICardProps) {
  const variantStyles: Record<string, string> = {
    default: 'card',
    alert: 'card border-destructive/30 bg-destructive/5',
    success: 'card border-success/30 bg-success/5',
    info: 'card border-info/30 bg-info/5',
  };

  const iconStyles: Record<string, string> = {
    default: 'bg-primary/15 text-primary',
    alert: 'bg-destructive/15 text-destructive',
    success: 'bg-success/15 text-success',
    info: 'bg-info/15 text-info',
  };

  const trendIsPositive = trend
    ? (trend.direction === 'up' && trend.good !== false) || (trend.direction === 'down' && trend.good === false)
    : null;

  return (
    <div className={`${variantStyles[variant]} p-5 flex flex-col gap-4 ${className} transition-all duration-200 hover:border-primary/30 hover:shadow-elevated`}>
      <div className="flex items-start justify-between">
        <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 ${iconStyles[variant]}`}>
          <Icon size={20} />
        </div>
        {trend && (
          <div className={`flex items-center gap-1 text-xs font-500 ${trendIsPositive ? 'text-success' : 'text-destructive'}`}>
            {trend.direction === 'up' ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
            <span>{trend.value}%</span>
          </div>
        )}
      </div>
      <div>
        <div className="stat-value mb-1">{value}</div>
        <div className="stat-label mb-1">{label}</div>
        <p className="text-xs text-muted-foreground">{subtext}</p>
      </div>
    </div>
  );
}

interface UserKPICardsProps {
  isLoading?: boolean;
}

export default function UserKPICards({ isLoading = false }: UserKPICardsProps) {
  if (isLoading) {
    return (
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="card p-5 space-y-4">
            <div className="skeleton w-10 h-10 rounded-xl" />
            <div className="space-y-2">
              <div className="skeleton h-8 w-16" />
              <div className="skeleton h-3 w-24" />
              <div className="skeleton h-3 w-32" />
            </div>
          </div>
        ))}
      </div>
    );
  }

  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <KPICard
        label="Videos Processed"
        value="14"
        subtext="3 processed today"
        icon={Upload}
        trend={{ value: 17, direction: 'up', good: true }}
        variant="info"
      />
      <KPICard
        label="Potholes Detected"
        value="87"
        subtext="Across 14 road segments"
        icon={MapPin}
        trend={{ value: 24, direction: 'up', good: true }}
        variant="default"
      />
      <KPICard
        label="Complaints Filed"
        value="61"
        subtext="Auto-generated by AI"
        icon={FileText}
        trend={{ value: 8, direction: 'up', good: true }}
        variant="success"
      />
      <KPICard
        label="Dangerous Unresolved"
        value="9"
        subtext="Requires immediate action"
        icon={AlertTriangle}
        trend={{ value: 12, direction: 'up', good: false }}
        variant="alert"
      />
    </div>
  );
}